name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Debug npm ci
        run: |
          npm list vite
          ls -la node_modules/.bin/ || echo "node_modules/.bin/ does not exist"
          if [ -f node_modules/.bin/vite ]; then echo "vite executable found"; else echo "vite executable not found"; fi
      - name: Verify vite installation
        run: |
          npx vite --version || echo "Failed to run vite --version"
      - name: Build the project
        run: npx vite build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: nutrition-tracker-3b0ef